apiVersion: v1
kind: PersistentVolume
metadata:
  name: dana-postgres-pv
  annotations:
    "volume.alpha.kubernetes.io/node-affinity": '{
      "requiredDuringSchedulingIgnoredDuringExecution": {
        "nodeSelectorTerms": [
          { "matchExpressions": [
            { "key": "kubernetes.io/hostname",
              "operator": "In",
              "values": ["minikube"]
            }
          ]}
         ]}
        }'
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-fast
  local:
    path: /data/dana-postgres-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dana-api-pv
  annotations:
    "volume.alpha.kubernetes.io/node-affinity": '{
      "requiredDuringSchedulingIgnoredDuringExecution": {
        "nodeSelectorTerms": [
          { "matchExpressions": [
            { "key": "kubernetes.io/hostname",
              "operator": "In",
              "values": ["minikube"]
            }
          ]}
         ]}
        }'
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-fast
  local:
    path: /data/dana-api-pv
