version: "3"
services:
  dana-nginx:
    image: dana-nginx:v0.1
    depends_on:
      - api
    ports:
      - "9000:80"
    environment:
      - NGINX_HOST=127.0.0.1.xip.io
      - NGINX_PORT=80
    command: /bin/bash -c "envsubst '$${NGINX_HOST},$${NGINX_PORT}'  < /etc/nginx/conf.d/dana-nginx.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  api:
    image: danapy:v0.1
    environment:
      FLASK_APP: dana.api.server
      YARGS_ENV: prod
    command: ["./wait-for-it.sh", "db:5432", "--", "uwsgi", "dana-uwsgi.ini"]
    expose:
      - "5000"
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: dana-api
      POSTGRES_USER: dana
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "./pgdata:/var/lib/postgresql/data/pgdata"
