version: "3"
services:
  api:
    image: danapy:v0.1
    environment:
      FLASK_APP: dana.api.server
      YARGS_ENV: prod
    command:
      python -m flask run --host=0.0.0.0
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: dana-api
      POSTGRES_USER: dana
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "./pgdata:/var/lib/postgresql/data/pgdata"
