version: "3"
services:
  dana-nginx:
    image: dana-nginx:${TAG}
    depends_on:
      - api
    ports:
      - "${NGINX_EXPOSE_PORT}:80"
    volumes:
      - "${DANA_UI_DIST}:/www"
    environment:
      - NGINX_HOST
      - IIIF_COOKIE
    command: /bin/bash -c "envsubst '$${NGINX_HOST},$${IIIF_COOKIE}'  < /etc/nginx/conf.d/dana-nginx.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  api:
    image: danapy:${TAG}
    environment:
      FLASK_APP: dana.api.server
      YARGS_ENV: prod
    command: ["./wait-for-it.sh", "db:5432", "--", "uwsgi", "dana-uwsgi.ini"]
    expose:
      - "5000"
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: dana-api
      POSTGRES_USER: dana
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "./pgdata:/var/lib/postgresql/data/pgdata"
