apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dana-api
  labels:
    app: dana
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dana
        tier: postgres
    spec:
      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim
      containers:
        - image: postgres:9.6
          name: postgres
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: dana-api
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dana
                  key: pg-password
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgresql/data/pgdata
