apiVersion: batch/v1
kind: Job
metadata:
  name: dana-db-migrate-head
spec:
  template:
    metadata:
      name: dana-db-migrate-head
    spec:
      restartPolicy: Never
      containers:
      - name: dana-db-migrate
        image: danapy:v0.1
        imagePullPolicy: Never
        command: ["alembic",  "upgrade", "head"]
        env:
          - name: YARGS_ENV
            value: prod
