apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: dana
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-fast
  resources:
    requests:
      storage: 20Gi
